export { Main } from './main/main.component'
export { Board } from './board/board.component'
export { Task } from './task/task.component'
export { Button } from './button/button.component'
export { Header } from './header/header.component'
export { Input } from './input/input.component'
