name: API Build

on:
  push:
    paths:
      - 'api/**'
    branches: [master]
  pull_request:
    paths:
      - 'api/**'
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build-api
